<a href="https://colab.research.google.com/github/SushantVij/NLP-CV-IOT-UCS657-/blob/main/102003759_NLP_in_Python_5_(Topic_Modeling)_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topic Modeling

## Introduction

Another popular text analysis technique is called topic modeling. The ultimate goal of topic modeling is to find various topics that are present in your corpus. Each document in the corpus will be made up of at least one topic, if not multiple topics.

In this notebook, we will be covering the steps on how to do **Latent Dirichlet Allocation (LDA)**, which is one of many topic modeling techniques. It was specifically designed for text data.

To use a topic modeling technique, you need to provide (1) a document-term matrix and (2) the number of topics you would like the algorithm to pick up.

Once the topic modeling technique is applied, your job as a human is to interpret the results and see if the mix of words in each topic make sense. If they don't make sense, you can try changing up the number of topics, the terms in the document-term matrix, model parameters, or even try a different model.

## Topic Modeling - Attempt #1 (All Text)

In [ ]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm.pkl')
data

,aa,aapologiesplease,aare,aautograph,abandoning,abbeythen,able,ableto,abletoto,aboardthe,...,youyoure,youyouve,yyou,yyoull,yyour,zero,zerothe,zerowho,zinc,zoneand
s1e1,0,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
s1e2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0
s1e3,0,0,0,1,0,0,0,0,0,1,...,2,1,1,0,0,0,0,0,2,0
s1e4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
s1e6,1,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e7,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
s1e8,0,0,0,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [ ]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [ ]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

                  s1e1  s1e2  s1e3  s1e4  s1e5  s1e6  s1e7  s1e8
aa                   0     0     0     0     0     1     0     0
aapologiesplease     0     0     0     0     0     1     0     0
aare                 1     0     0     0     0     0     0     0
aautograph           0     0     1     0     0     0     0     0
abandoning           0     0     0     0     0     0     0     1

This code creates a document-term matrix (tdm) and converts it into a scipy sparse matrix (sparse_counts). The sparse matrix is then converted into a corpus object (corpus) using the matutils library. The corpus object is used for further analysis in natural language processing.

In [ ]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [ ]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [ ]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.010*"know" + 0.008*"just" + 0.008*"dont" + 0.008*"fucking" + 0.007*"got" + 0.006*"im" + 0.005*"right" + 0.005*"like" + 0.005*"gonna" + 0.004*"want"'),
 (1,
  '0.005*"know" + 0.005*"just" + 0.005*"dont" + 0.004*"im" + 0.004*"like" + 0.004*"gonna" + 0.004*"fucking" + 0.004*"got" + 0.003*"mean" + 0.003*"right"')]

In [ ]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.008*"just" + 0.007*"know" + 0.006*"got" + 0.006*"dont" + 0.006*"im" + 0.004*"like" + 0.004*"right" + 0.004*"gonna" + 0.004*"mean" + 0.003*"yeah"'),
 (1,
  '0.010*"know" + 0.008*"fucking" + 0.008*"dont" + 0.008*"just" + 0.006*"im" + 0.006*"got" + 0.006*"gonna" + 0.006*"like" + 0.005*"right" + 0.005*"want"'),
 (2,
  '0.008*"know" + 0.006*"fucking" + 0.005*"dont" + 0.005*"just" + 0.005*"im" + 0.005*"got" + 0.003*"like" + 0.003*"think" + 0.003*"come" + 0.003*"right"')]

In [ ]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.007*"just" + 0.006*"got" + 0.006*"know" + 0.005*"right" + 0.005*"dont" + 0.004*"yeah" + 0.004*"im" + 0.003*"gonna" + 0.003*"like" + 0.003*"youre"'),
 (1,
  '0.000*"know" + 0.000*"im" + 0.000*"just" + 0.000*"dont" + 0.000*"fucking" + 0.000*"like" + 0.000*"gonna" + 0.000*"got" + 0.000*"right" + 0.000*"youre"'),
 (2,
  '0.007*"know" + 0.006*"dont" + 0.005*"im" + 0.005*"just" + 0.004*"fucking" + 0.004*"got" + 0.004*"mean" + 0.003*"yeah" + 0.003*"come" + 0.003*"want"'),
 (3,
  '0.012*"know" + 0.009*"just" + 0.009*"fucking" + 0.009*"dont" + 0.007*"im" + 0.007*"got" + 0.006*"like" + 0.006*"gonna" + 0.005*"right" + 0.005*"want"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [ ]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [ ]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                             transcript
s1e1  yo i am so psychedfor invisible force  force  ...
s1e2  so youreyoure not a feddo you hear thatthats t...
s1e3  ill take thismercisorry about all theoh dont b...
s1e4   come on mmmm just come with nuhuh please no f...
s1e5  hey baby oh jesus christ yeah im sorrywhere ha...
s1e6  obviously a lot of its tempi love itif were ai...
s1e7  ho ho ho merry christmaswhos been naughty it i...
s1e8  howdy boysoh sorrysorry sorry sorry sorryhow a...

In [ ]:
# Apply the nouns function to the transcripts to filter only on nouns
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

                                             transcript
s1e1  yo i force force translucent deeps hes invisib...
s1e2  feddo billso gotamericas invisiblewanker dead ...
s1e3  ill thismercisorry theoh himah care itthethe u...
s1e4  mmmm please waythis reunion everyeah i hope ba...
s1e5  hey baby jesus christ yeah im beenhandling bus...
s1e6  lot tempi love itif people worldbut reality ga...
s1e7  ho ho ho merry center brand mmhmm picture i pi...
s1e8  howdy boysoh sorrysorry sorry sorry sorryhow d...

In [ ]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words='english')
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names_out())
data_dtmn.index = data_nouns.index
data_dtmn

,aapologiesplease,aare,abbeythen,aboardthe,aboutand,aboutbecause,abouthow,aboutmy,abouton,aboutthats,...,youyoull,youyour,youyoure,youyouve,yyou,yyour,zero,zerothe,zinc,zoneand
s1e1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e2,0,0,0,0,0,0,0,0,0,0,...,1,1,0,0,0,0,1,0,0,0
s1e3,0,0,0,1,0,0,1,0,0,0,...,0,0,2,1,0,0,0,0,2,0
s1e4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e5,0,0,0,0,0,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,0
s1e6,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e7,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,1,0,0
s1e8,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,1,0,0,0,1

In [ ]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [ ]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.007*"dont" + 0.007*"youre" + 0.005*"im" + 0.005*"gon" + 0.004*"thats" + 0.004*"yeah" + 0.003*"fuck" + 0.003*"mean" + 0.003*"fucking" + 0.003*"hes"'),
 (1,
  '0.008*"dont" + 0.006*"im" + 0.006*"youre" + 0.005*"fucking" + 0.004*"gon" + 0.004*"fuck" + 0.004*"thats" + 0.003*"mean" + 0.003*"hey" + 0.003*"wait"')]

In [ ]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.008*"dont" + 0.007*"im" + 0.006*"youre" + 0.004*"mean" + 0.004*"fucking" + 0.004*"thats" + 0.004*"gon" + 0.003*"hey" + 0.003*"yeah" + 0.002*"sorry"'),
 (1,
  '0.009*"dont" + 0.009*"youre" + 0.006*"gon" + 0.005*"im" + 0.005*"yeah" + 0.005*"fuck" + 0.004*"fucking" + 0.003*"didnt" + 0.003*"thats" + 0.003*"mean"'),
 (2,
  '0.006*"dont" + 0.005*"thats" + 0.005*"fuck" + 0.004*"youre" + 0.004*"im" + 0.004*"gon" + 0.003*"fucking" + 0.003*"hes" + 0.002*"yeah" + 0.002*"didnt"')]

In [ ]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.004*"fuck" + 0.004*"fucking" + 0.004*"dont" + 0.003*"im" + 0.003*"thats" + 0.003*"gon" + 0.003*"water" + 0.003*"hes" + 0.003*"wait" + 0.002*"youre"'),
 (1,
  '0.007*"dont" + 0.006*"im" + 0.006*"youre" + 0.004*"gon" + 0.004*"yeah" + 0.003*"thats" + 0.003*"hey" + 0.003*"mean" + 0.002*"hes" + 0.002*"kind"'),
 (2,
  '0.006*"dont" + 0.005*"youre" + 0.005*"thats" + 0.003*"im" + 0.003*"gon" + 0.003*"fuck" + 0.003*"yeah" + 0.003*"hes" + 0.003*"lets" + 0.002*"mean"'),
 (3,
  '0.011*"dont" + 0.010*"youre" + 0.008*"im" + 0.006*"fucking" + 0.006*"gon" + 0.005*"mean" + 0.005*"thats" + 0.005*"fuck" + 0.005*"yeah" + 0.004*"sorry"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [ ]:
# Let's create a function to pull out nouns and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [ ]:
# Apply the nouns function to the transcripts to filter only on nouns and adjectives
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                             transcript
s1e1  yo i psychedfor invisible force force deep uhh...
s1e2  feddo old billso youve gotamericas favorite in...
s1e3  ill thismercisorry theoh himah care itthethe u...
s1e4  mmmm nuhuh please waythis last reunion everyea...
s1e5  hey baby jesus christ yeah im daysyeah ive bee...
s1e6  lot tempi love itif tlcbetween lifeand little ...
s1e7  ho ho ho merry naughty dead center brand mmhmm...
s1e8  howdy boysoh sorrysorry sorry sorry sorryhow g...

In [ ]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words='english', max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aapologiesplease,aare,aautograph,abbeythen,able,ableto,aboardthe,aboutand,aboutbecause,abouthow,...,youyoull,youyour,youyoure,youyouve,yyou,yyour,zero,zerothe,zinc,zoneand
s1e1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e2,0,0,0,0,0,1,0,0,0,0,...,1,2,0,0,0,0,1,0,0,0
s1e3,0,0,1,0,0,0,1,0,0,1,...,0,0,2,1,1,0,0,0,2,0
s1e4,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
s1e6,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e7,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
s1e8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1

In [ ]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [ ]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.002*"whoa" + 0.002*"wait" + 0.001*"ii" + 0.001*"youi" + 0.001*"doesnt" + 0.001*"translucent" + 0.001*"youyou" + 0.001*"job" + 0.001*"bit" + 0.001*"meto"'),
 (1,
  '0.002*"new" + 0.002*"youyou" + 0.002*"baby" + 0.002*"stop" + 0.001*"shes" + 0.001*"guy" + 0.001*"wait" + 0.001*"bit" + 0.001*"filthy" + 0.001*"red"')]

In [ ]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.003*"new" + 0.002*"youyou" + 0.002*"ii" + 0.002*"wait" + 0.002*"red" + 0.001*"bit" + 0.001*"whoa" + 0.001*"shes" + 0.001*"stop" + 0.001*"job"'),
 (1,
  '0.002*"whoa" + 0.001*"wait" + 0.001*"water" + 0.001*"plane" + 0.001*"flight" + 0.001*"youyou" + 0.001*"youi" + 0.001*"girl" + 0.001*"theyre" + 0.001*"deep"'),
 (2,
  '0.002*"stop" + 0.002*"baby" + 0.002*"wait" + 0.002*"doesnt" + 0.002*"youi" + 0.002*"bit" + 0.001*"meyou" + 0.001*"youve" + 0.001*"guy" + 0.001*"son"')]

In [ ]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.002*"youyou" + 0.002*"spice" + 0.002*"plane" + 0.002*"shes" + 0.002*"flight" + 0.001*"whoa" + 0.001*"son" + 0.001*"id" + 0.001*"mm" + 0.001*"gang"'),
 (1,
  '0.003*"stop" + 0.002*"doesnt" + 0.002*"wait" + 0.002*"youi" + 0.002*"baby" + 0.002*"meyou" + 0.001*"new" + 0.001*"better" + 0.001*"youve" + 0.001*"job"'),
 (2,
  '0.002*"new" + 0.002*"wait" + 0.002*"youyou" + 0.001*"whoa" + 0.001*"ii" + 0.001*"bit" + 0.001*"water" + 0.001*"love" + 0.001*"ready" + 0.001*"baby"'),
 (3,
  '0.002*"wait" + 0.002*"whoa" + 0.002*"ii" + 0.001*"youyou" + 0.001*"bit" + 0.001*"cable" + 0.001*"ityou" + 0.001*"dad" + 0.001*"bug" + 0.001*"red"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [ ]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.003*"youyou" + 0.002*"new" + 0.002*"whoa" + 0.002*"wait" + 0.001*"shes" + 0.001*"home" + 0.001*"ass" + 0.001*"id" + 0.001*"red" + 0.001*"rest"'),
 (1,
  '0.003*"whoa" + 0.002*"water" + 0.002*"wait" + 0.002*"skin" + 0.001*"times" + 0.001*"ready" + 0.001*"translucent" + 0.001*"girl" + 0.001*"matter" + 0.001*"mmhmm"'),
 (2,
  '0.002*"secrets" + 0.001*"ii" + 0.001*"new" + 0.001*"support" + 0.001*"hero" + 0.001*"fan" + 0.001*"american" + 0.001*"safe" + 0.001*"mom" + 0.001*"red"'),
 (3,
  '0.002*"baby" + 0.002*"stop" + 0.002*"wait" + 0.002*"youi" + 0.002*"doesnt" + 0.002*"bit" + 0.002*"youve" + 0.002*"guy" + 0.002*"flight" + 0.002*"meyou"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: food
* Topic 1: party
* Topic 2: friends
* Topic 3: profanity

In [ ]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(0, 's1e1'),
 (1, 's1e2'),
 (0, 's1e3'),
 (0, 's1e4'),
 (3, 's1e5'),
 (2, 's1e6'),
 (3, 's1e7'),
 (3, 's1e8')]

For a first pass of LDA, these kind of make sense to me, so we'll call it a day for now.
* Topic 0: food [Bill,Trevor,Whitney]
* Topic 1: party [Antony,Jim,Ricky]
* Topic 2: friends [Dave,Kenny,Mike]
* Topic 3: profanity [Ali,Eric,George,Joe,John,Louis,Pete,Taylor,Tom]

### Assignment:
1. Try further modifying the parameters of the topic models above and see if you can get better topics.
2. Create a new topic model that includes terms from a different [part of speech](https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html) and see if you can get better topics.

In [ ]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words='english', max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

In [ ]:
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said', 'fuck', 'fucking','fck','sex']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)
cvna = CountVectorizer(stop_words='english', max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aapologiesplease,aare,aautograph,abbeythen,able,ableto,aboardthe,aboutand,aboutbecause,abouthow,...,youyoull,youyour,youyoure,youyouve,yyou,yyour,zero,zerothe,zinc,zoneand
s1e1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e2,0,0,0,0,0,1,0,0,0,0,...,1,2,0,0,0,0,1,0,0,0
s1e3,0,0,1,0,0,0,1,0,0,1,...,0,0,2,1,1,0,0,0,2,0
s1e4,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
s1e6,1,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e7,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
s1e8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,1,0,0,0,1

In [ ]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [ ]:
ldana = models.LdaModel(corpus=corpusna, num_topics=8, id2word=id2wordna, passes=15, alpha='auto', eta='auto', chunksize=2000, minimum_probability=0.002)
ldana.print_topics()

[(0,
  '0.005*"new" + 0.002*"meyou" + 0.002*"job" + 0.002*"care" + 0.002*"youi" + 0.002*"baby" + 0.002*"iti" + 0.002*"milk" + 0.002*"fastest" + 0.002*"happy"'),
 (1,
  '0.003*"youyou" + 0.003*"whoa" + 0.002*"wait" + 0.002*"id" + 0.002*"son" + 0.002*"flight" + 0.002*"rest" + 0.002*"shes" + 0.002*"ii" + 0.002*"spice"'),
 (2,
  '0.000*"wait" + 0.000*"whoa" + 0.000*"youyou" + 0.000*"ii" + 0.000*"ityou" + 0.000*"doesnt" + 0.000*"love" + 0.000*"red" + 0.000*"bit" + 0.000*"stop"'),
 (3,
  '0.000*"youyou" + 0.000*"wait" + 0.000*"whoa" + 0.000*"doesnt" + 0.000*"bit" + 0.000*"new" + 0.000*"baby" + 0.000*"flight" + 0.000*"job" + 0.000*"ii"'),
 (4,
  '0.003*"stop" + 0.002*"doesnt" + 0.002*"wait" + 0.002*"shes" + 0.002*"secrets" + 0.002*"new" + 0.002*"red" + 0.002*"youyou" + 0.002*"dad" + 0.002*"baby"'),
 (5,
  '0.000*"wait" + 0.000*"ii" + 0.000*"youyou" + 0.000*"bit" + 0.000*"whoa" + 0.000*"new" + 0.000*"shes" + 0.000*"flight" + 0.000*"stop" + 0.000*"job"'),
 (6,
  '0.000*"new" + 0.000*"wait" + 0.000*"stop" + 0.000*"whoa" + 0.000*"youyou" + 0.000*"baby" + 0.000*"youi" + 0.000*"red" + 0.000*"ii" + 0.000*"shes"'),
 (7,
  '0.003*"whoa" + 0.003*"wait" + 0.002*"water" + 0.002*"flight" + 0.002*"bit" + 0.002*"theyre" + 0.002*"girl" + 0.002*"ready" + 0.002*"need" + 0.002*"love"')]

In [ ]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(1, 's1e1'),
 (7, 's1e2'),
 (0, 's1e3'),
 (1, 's1e4'),
 (7, 's1e5'),
 (4, 's1e6'),
 (4, 's1e7'),
 (0, 's1e8')]

In [ ]:
# Let's create a function to pull out nouns,verbs and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'VB' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [ ]:
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                             transcript
s1e1  yo i am psychedfor invisible force force was l...
s1e2  feddo hear old billso want explainwhy youve go...
s1e3  ill take thismercisorry theoh dont be stupidyo...
s1e4  come mmmm come nuhuh please fucking waythis be...
s1e5  hey baby jesus christ yeah im have beenits bee...
s1e6  lot tempi love itif were airing tlcbetween lif...
s1e7  ho ho ho merry christmaswhos been naughty is d...
s1e8  howdy boysoh sorrysorry sorry sorry sorryhow a...

In [ ]:
cvna = CountVectorizer(stop_words='english', max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,aa,aapologiesplease,aare,aautograph,abandoning,abbeythen,able,ableto,aboardthe,abouta,...,youyoure,youyouve,yyou,yyoull,yyour,zero,zerothe,zerowho,zinc,zoneand
s1e1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0
s1e3,0,0,0,1,0,0,0,0,1,0,...,2,1,1,0,0,0,0,0,2,0
s1e4,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
s1e6,1,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
s1e7,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
s1e8,0,0,0,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,1

In [ ]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [ ]:
ldana = models.LdaModel(corpus=corpusna, num_topics=5,alpha='auto', eta='auto',chunksize=1000, minimum_probability=0.002,id2word=id2wordna, passes=15)
ldana.print_topics()

WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive
WARNING:gensim.models.ldamodel:updated prior is not positive

[(0,
  '0.002*"new" + 0.001*"whoa" + 0.001*"shes" + 0.001*"hughie" + 0.001*"save" + 0.001*"sign" + 0.001*"ass" + 0.001*"rest" + 0.001*"son" + 0.001*"id"'),
 (1,
  '0.002*"baby" + 0.002*"kill" + 0.002*"meet" + 0.001*"hughie" + 0.001*"dad" + 0.001*"guy" + 0.001*"youve" + 0.001*"whoa" + 0.001*"shes" + 0.001*"youi"'),
 (2,
  '0.003*"meyou" + 0.002*"youi" + 0.002*"wanted" + 0.001*"kill" + 0.001*"new" + 0.001*"iti" + 0.001*"gave" + 0.001*"scared" + 0.001*"boys" + 0.001*"promised"'),
 (3,
  '0.002*"seen" + 0.001*"wanted" + 0.001*"cut" + 0.001*"secrets" + 0.001*"new" + 0.001*"believe" + 0.001*"trying" + 0.001*"used" + 0.001*"wouldnt" + 0.001*"mom"'),
 (4,
  '0.002*"whoa" + 0.002*"kill" + 0.002*"believe" + 0.002*"theyre" + 0.001*"water" + 0.001*"flight" + 0.001*"bit" + 0.001*"feel" + 0.001*"mmhmm" + 0.001*"wouldnt"')]

In [ ]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(0, 's1e1'),
 (4, 's1e2'),
 (0, 's1e3'),
 (0, 's1e4'),
 (4, 's1e5'),
 (3, 's1e6'),
 (1, 's1e7'),
 (2, 's1e8')]